In [1]:
import numpy as np

In [2]:
a=np.array([[1,0],[2,1]])
a=a.repeat(2,axis=1).repeat(2,axis=0)
b=np.array([[1,2],[3,4]])
b=np.tile(b,(2,2))
np.multiply(b,a)

array([[1, 2, 0, 0],
       [3, 4, 0, 0],
       [2, 4, 1, 2],
       [6, 8, 3, 4]])

In [6]:
a

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [2, 2, 1, 1],
       [2, 2, 1, 1]])

In [9]:
a.reshape(16,1).shape

(16, 1)

In [21]:
p=4
m=3
su_=np.zeros((p,m))
for i in range(p):
    for j in range(m):
        if (i>=j):
            su_[i,j]=i+1-j 
su_=su_.repeat(2,axis=1).repeat(3,axis=0)
su_

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [2., 2., 1., 1., 0., 0.],
       [2., 2., 1., 1., 0., 0.],
       [2., 2., 1., 1., 0., 0.],
       [3., 3., 2., 2., 1., 1.],
       [3., 3., 2., 2., 1., 1.],
       [3., 3., 2., 2., 1., 1.],
       [4., 4., 3., 3., 2., 2.],
       [4., 4., 3., 3., 2., 2.],
       [4., 4., 3., 3., 2., 2.]])

In [54]:
np.tile(np.array([3,4]),(1,p))

array([[3, 4, 3, 4, 3, 4, 3, 4]])

In [36]:
import casadi

In [52]:
H = casadi.DM(np.eye(2))
A = casadi.DM(np.ones((1,2)))
g = casadi.DM(np.zeros(2))
lba = 10.

qp = {}
qp['h'] = H.sparsity()
qp['a'] = A.sparsity()
S = casadi.conic('S','qpoases',qp)
print(S)





r = S(h=H, g=g, a=A, lba=lba)
x_opt = r['x']
print('x_opt: ', x_opt)

S:(h[2x2],g[2],a[1x2],lba,uba,lbx[2],ubx[2],x0[2],lam_x0[2],lam_a0,q[],p[])->(x[2],cost,lam_a,lam_x[2]) QpoasesInterface


####################   qpOASES  --  QP NO.   1   #####################

    Iter   |    StepLength    |       Info       |   nFX   |   nAC    
 ----------+------------------+------------------+---------+--------- 
       0   |   1.866661e-007   |   ADD CON    0   |     1   |     1   
       1   |   1.333333e-008   |   REM BND    1   |     0   |     1   
       2   |   1.000000e+000   |    QP SOLVED     |     0   |     1   
x_opt:  [5, 5]


In [44]:
H

array([[1., 0.],
       [0., 1.]])